#!/usr/bin/env python3
"""Reference Mobitec frames produced by the legacy Raspberry Pi code.

Takes ConvertMobitecImage, SendMobitecImage, AddHeader and AddChecksum
verbatim from legacy/rpi/scripts/futaba.py (the module itself needs the
Pi hardware libraries, so only these functions are extracted), feeds them
test images and writes fw/tests/golden/futaba_gen.h for the ztest suite.

    python3 tools/glyphgen/futaba_vectors.py [--check]
"""
import ast
import os
import sys
import tempfile

from PIL import Image

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
SRC = os.path.join(ROOT, "legacy/rpi/scripts/futaba.py")
OUT = os.path.join(ROOT, "fw/tests/golden/futaba_gen.h")
W, H = 102, 11
FUNCS = {"ConvertMobitecImage", "SendMobitecImage", "AddHeader", "AddChecksum"}


def load_legacy():
    tree = ast.parse(open(SRC, encoding="utf-8").read())
    body = [n for n in tree.body if isinstance(n, ast.FunctionDef) and n.name in FUNCS]
    ns = {"Image": Image}
    exec(compile(ast.Module(body=body, type_ignores=[]), SRC, "exec"), ns)
    return ns


def frames():
    """Test frames as sets of lit (x, y)."""
    yield "checker", {(x, y) for x in range(W) for y in range(H) if (x + y) % 2 == 0}
    yield "columns", {(x, y) for x in range(W) for y in range(H) if x % 2 == 0}
    yield "rows", {(x, y) for x in range(W) for y in range(H) if y % 2 == 0}
    yield "border", {(x, y) for x in range(W) for y in range(H)
                     if x in (0, W - 1) or y in (0, H - 1)}
    yield "diagonal", {(x, x % H) for x in range(W)}


def legacy_bytes(ns, lit):
    # The legacy code splits an image into bands with int(h/4) + int(h%4);
    # a 12 row image gives exactly the three bands of the 11 row sign.
    img = Image.new("L", (W, 12), 0)
    for (x, y) in lit:
        img.putpixel((x, y), 255)
    with tempfile.TemporaryDirectory() as d:
        p = os.path.join(d, "f.png")
        img.save(p)
        hex_arr, pw, ph = ns["ConvertMobitecImage"](p, False)
    msg = ns["AddHeader"](bytearray())
    msg = ns["SendMobitecImage"](msg, hex_arr, pw, ph, 0)
    return bytes(ns["AddChecksum"](msg))


def frame_bytes(lit):
    b = [0] * ((W * H + 7) // 8)
    for (x, y) in lit:
        i = y * W + x
        b[i >> 3] |= 1 << (i & 7)
    return b


def render():
    ns = load_legacy()
    out = ["/* Generated by tools/glyphgen/futaba_vectors.py from legacy/rpi/scripts/futaba.py. */",
           "#ifndef FUTABA_GEN_H_", "#define FUTABA_GEN_H_", "#include <stdint.h>", "",
           "struct futaba_case { const char *name; uint8_t frame[141]; const uint8_t *bytes; int len; };"]
    cases = []
    for i, (name, lit) in enumerate(frames()):
        mob = legacy_bytes(ns, lit)
        out.append(f"static const uint8_t futaba_bytes_{i}[] = {{{','.join(f'0x{b:02x}' for b in mob)}}};")
        fb = ",".join(f"0x{b:02x}" for b in frame_bytes(lit))
        cases.append(f'\t{{"{name}", {{{fb}}}, futaba_bytes_{i}, {len(mob)}}}')
    out.append("static const struct futaba_case futaba_cases[] = {\n" + ",\n".join(cases) + "\n};")
    out.append("#endif")
    return "\n".join(out) + "\n"


def main():
    content = render()
    old = open(OUT, encoding="utf-8").read() if os.path.exists(OUT) else None
    if old == content:
        return 0
    if "--check" in sys.argv:
        print(f"stale: {os.path.relpath(OUT, ROOT)}; run python3 tools/glyphgen/futaba_vectors.py")
        return 1
    with open(OUT, "w", encoding="utf-8") as f:
        f.write(content)
    print(f"wrote {os.path.relpath(OUT, ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
