#!/usr/bin/env node
// Generates firmware glyph tables from tools/sign-simulator/core.js.
//
//   node tools/glyphgen/glyphgen.js            write outputs
//   node tools/glyphgen/glyphgen.js --check    fail if outputs are stale
//
// Outputs:
//   fw/lib/sign/glyphs_gen.h   C tables (fonts, icons, arrows, pictograms)
//   fw/web/src/glyphs.json     same data for the browser renderer and Node tests
'use strict';
const fs = require('fs');
const path = require('path');
const core = require('../sign-simulator/core.js');

const ROOT = path.resolve(__dirname, '../..');
const OUT_H = path.join(ROOT, 'fw/lib/sign/glyphs_gen.h');
const OUT_JSON = path.join(ROOT, 'fw/web/src/glyphs.json');

// Fixed orders: the C enums depend on them.
const COND = ['clear', 'night', 'pcloud', 'pcloud_n', 'cloudy', 'rain', 'snow', 'storm'];
const DIRS = ['n', 'ne', 'e', 'se', 's', 'sw', 'w', 'nw'];
const TRENDS = ['up', 'down', 'flat'];
const PICTOS = Object.keys(core.PICTO);

function check(rows, what) {
  const w = rows[0].length;
  if (w > 16) throw new Error(`${what}: too wide`);
  rows.forEach((r) => { if (r.length !== w) throw new Error(`${what}: ragged`); });
  return w;
}

function rowsToBits(rows) {
  const w = rows[0].length;
  return rows.map((r) => {
    let v = 0;
    for (let x = 0; x < w; x++) if (r[x] === '#') v |= 1 << (w - 1 - x);
    return v;
  });
}

function hex(v) { return '0x' + v.toString(16).padStart(4, '0'); }

function cBitmap(rows, what) {
  const w = check(rows, what);
  return `{ ${w}, ${rows.length}, { ${rowsToBits(rows).map(hex).join(', ')} } }`;
}

function cFont(name, font, h) {
  const cps = Object.keys(font).map((ch) => ch.codePointAt(0)).sort((a, b) => a - b);
  const lines = cps.map((cp) => {
    const ch = String.fromCodePoint(cp);
    const rows = font[ch];
    if (rows.length !== h) throw new Error(`${name} '${ch}': height ${rows.length}`);
    const label = cp < 0x7f ? ch.replace('\\', '\\\\') : `U+${cp.toString(16).toUpperCase()}`;
    return `\t{ 0x${cp.toString(16)}, ${cBitmap(rows, name + ch)} }, /* ${label} */`;
  });
  return `static const struct ws_glyph ${name}_glyphs[] = {\n${lines.join('\n')}\n};\n`;
}

function genC() {
  const o = [];
  o.push('/* Generated by tools/glyphgen/glyphgen.js from tools/sign-simulator/core.js.');
  o.push(' * Do not edit: change core.js and regenerate. */');
  o.push('#ifndef WS_GLYPHS_GEN_H_\n#define WS_GLYPHS_GEN_H_\n');
  o.push('/* Bitmaps: one uint16 per row, bit (w - 1 - x) is column x. */\n');
  o.push(cFont('ws_big', core.BIG, 11));
  o.push(cFont('ws_small', core.SM, 5));
  o.push('/* Weather icons 11x11, order of enum ws_cond. */');
  o.push('static const struct ws_bitmap ws_icon_l[] = {');
  COND.forEach((c) => o.push(`\t${cBitmap(core.ICON[c], c)}, /* ${c} */`));
  o.push('};\n');
  o.push('/* Weather icons 5x5, order of enum ws_cond. */');
  o.push('static const struct ws_bitmap ws_icon_s[] = {');
  COND.forEach((c) => o.push(`\t${cBitmap(core.ICON_S[c], c)}, /* ${c} */`));
  o.push('};\n');
  o.push('/* Wind arrows 5x5 pointing where the wind blows, order of enum ws_dir. */');
  o.push('static const struct ws_bitmap ws_wind_arrows[] = {');
  DIRS.forEach((d) => o.push(`\t${cBitmap(core.WIND[d], d)}, /* ${d} */`));
  o.push('};\n');
  o.push('/* Pressure trend arrows 5x5: up, down, flat. */');
  o.push('static const struct ws_bitmap ws_trend_arrows[] = {');
  TRENDS.forEach((t) => o.push(`\t${cBitmap(core.TREND[t], t)}, /* ${t} */`));
  o.push('};\n');
  o.push('/* Built-in pictograms: 11x11 and 5x5. */');
  o.push('static const struct ws_picto_builtin ws_pictos[] = {');
  PICTOS.forEach((p) => o.push(`\t{ "${p}", ${cBitmap(core.PICTO[p].L, p)},\n\t  ${cBitmap(core.PICTO[p].S, p)} },`));
  o.push('};\n');
  o.push('#endif /* WS_GLYPHS_GEN_H_ */\n');
  return o.join('\n');
}

function genJson() {
  const out = {
    w: core.W, h: core.H,
    big: core.BIG, small: core.SM,
    cond: COND, dirs: DIRS,
    icon_l: Object.fromEntries(COND.map((c) => [c, core.ICON[c]])),
    icon_s: Object.fromEntries(COND.map((c) => [c, core.ICON_S[c]])),
    wind: Object.fromEntries(DIRS.map((d) => [d, core.WIND[d]])),
    trend: core.TREND,
    pictos: Object.fromEntries(PICTOS.map((p) => [p, { L: core.PICTO[p].L, S: core.PICTO[p].S }])),
  };
  return JSON.stringify(out) + '\n';
}

function main() {
  const checkOnly = process.argv.includes('--check');
  const outputs = [[OUT_H, genC()], [OUT_JSON, genJson()]];
  let stale = false;
  for (const [file, content] of outputs) {
    const old = fs.existsSync(file) ? fs.readFileSync(file, 'utf8') : null;
    if (old === content) continue;
    if (checkOnly) {
      console.error(`stale: ${path.relative(ROOT, file)}`);
      stale = true;
    } else {
      fs.mkdirSync(path.dirname(file), { recursive: true });
      fs.writeFileSync(file, content);
      console.log(`wrote ${path.relative(ROOT, file)}`);
    }
  }
  if (stale) {
    console.error('Run: node tools/glyphgen/glyphgen.js');
    process.exit(1);
  }
}

module.exports = { COND, DIRS, TRENDS, PICTOS };
if (require.main === module) main();
