/*
 * HTTP server: gzip static pages and the REST API with Basic Auth
 * (fw/README.md, spec sections 7 and 10). Without a password set, and in
 * access point mode, the API is open so the device can be set up.
 */
#include <errno.h>
#include <string.h>
#include <strings.h>

#include <zephyr/kernel.h>
#include <zephyr/logging/log.h>
#include <zephyr/net/http/server.h>
#include <zephyr/net/http/service.h>

#include <ws/util.h>

#include "app.h"
#include "ota/ota.h"
#include "web.h"
#ifdef CONFIG_WS_NET
#include "net/net_mgr.h"
#endif

LOG_MODULE_REGISTER(ws_web, LOG_LEVEL_INF);

HTTP_SERVER_REGISTER_HEADER_CAPTURE(ws_hdr_auth, "Authorization");

static uint16_t http_port = CONFIG_WS_HTTP_PORT;
HTTP_SERVICE_DEFINE(ws_http, NULL, &http_port, CONFIG_HTTP_SERVER_MAX_CLIENTS, 10, NULL, NULL,
		    NULL);

/* ---- static resources (gzip, generated by fw/web/web.cmake) ---- */

static const uint8_t index_gz[] = {
#include "index.html.gz.inc"
};
static const uint8_t app_js_gz[] = {
#include "app.js.gz.inc"
};
static const uint8_t render_js_gz[] = {
#include "render.js.gz.inc"
};
static const uint8_t style_gz[] = {
#include "style.css.gz.inc"
};

#define STATIC_GZ(_name, _path, _type)                                                             \
	static struct http_resource_detail_static _name##_detail = {                               \
		.common = {.type = HTTP_RESOURCE_TYPE_STATIC,                                      \
			   .bitmask_of_supported_http_methods = BIT(HTTP_GET),                     \
			   .content_encoding = "gzip",                                             \
			   .content_type = _type},                                                 \
		.static_data = _name##_gz,                                                         \
		.static_data_len = sizeof(_name##_gz),                                             \
	};                                                                                         \
	HTTP_RESOURCE_DEFINE(_name##_res, ws_http, _path, &_name##_detail)

STATIC_GZ(index, "/", "text/html; charset=utf-8");
STATIC_GZ(app_js, "/app.js", "text/javascript; charset=utf-8");
STATIC_GZ(render_js, "/render.js", "text/javascript; charset=utf-8");
STATIC_GZ(style, "/style.css", "text/css; charset=utf-8");

/* ---- API plumbing ---- */

static WS_BIG_BSS char resp_buf[WS_WEB_RESP_MAX];
static const struct http_header json_headers[] = {
	{.name = "Content-Type", .value = "application/json; charset=utf-8"},
	{.name = "Cache-Control", .value = "no-store"},
};
static const struct http_header auth_headers[] = {
	{.name = "Content-Type", .value = "application/json; charset=utf-8"},
	{.name = "WWW-Authenticate", .value = "Basic realm=\"weatherstation\""},
};

struct route {
	api_fn fn;
	bool big_body; /* body up to 32 KB in the shared JSON buffer */
	/* per request state (a dynamic resource serves one client at a time) */
	char *body;
	size_t len;
	size_t cap;
	bool overflow;
	bool holds_json_buf;
	/* bodies of the small requests (lamp, pin...); big ones use the JSON buffer */
	char small[512];
};

void api_error(struct api_resp *r, int status, const char *msg)
{
	struct ws_jw w;

	ws_jw_init(&w, r->buf, r->cap);
	ws_jw_obj(&w);
	ws_jw_kstr(&w, "error", msg);
	ws_jw_obj_end(&w);
	r->status = status;
	r->len = w.pos;
}

void api_json(struct api_resp *r, int status, struct ws_jw *w)
{
	if (!w->ok) {
		api_error(r, HTTP_500_INTERNAL_SERVER_ERROR, "ответ не помещается в буфер");
		return;
	}
	r->status = status;
	r->len = w->pos;
}

static bool authorized(const struct http_request_ctx *req)
{
	struct ws_settings s;
	char dec[96];

#ifdef CONFIG_WS_NET
	if (!strcmp(ws_net_state_str(), "ap")) {
		ws_net_activity();
		return true;
	}
#endif
	ws_app_settings_get(&s);
	if (!s.web_hash[0]) {
		return true;
	}
	for (size_t i = 0; i < req->header_count; i++) {
		const struct http_header *h = &req->headers[i];

		if (strcasecmp(h->name, "Authorization") || strncmp(h->value, "Basic ", 6)) {
			continue;
		}
		int n = ws_base64_decode(h->value + 6, strlen(h->value + 6), (uint8_t *)dec,
					 sizeof(dec) - 1);

		if (n <= 0) {
			return false;
		}
		dec[n] = '\0';
		char *colon = strchr(dec, ':');

		if (!colon) {
			return false;
		}
		*colon = '\0';
		return strcmp(dec, s.web_user) == 0 && ws_settings_check_password(&s, colon + 1);
	}
	return false;
}

static void release(struct route *rt)
{
	if (rt->holds_json_buf) {
		ws_app_json_buf_give();
		rt->holds_json_buf = false;
	}
	rt->body = NULL;
	rt->len = 0;
	rt->overflow = false;
}

static int api_cb(struct http_client_ctx *client, enum http_data_status status,
		  const struct http_request_ctx *req, struct http_response_ctx *resp,
		  void *user_data)
{
	struct route *rt = user_data;

	if (status == HTTP_SERVER_DATA_ABORTED) {
		release(rt);
		return 0;
	}
	if (!rt->body) {
		if (rt->big_body) {
			rt->body = ws_app_json_buf_take(K_SECONDS(5));
			if (!rt->body) {
				resp->status = HTTP_503_SERVICE_UNAVAILABLE;
				resp->final_chunk = status == HTTP_SERVER_DATA_FINAL;
				return 0;
			}
			rt->holds_json_buf = true;
			rt->cap = WS_MAX_FILE;
		} else {
			rt->body = rt->small;
			rt->cap = sizeof(rt->small) - 1;
		}
		rt->len = 0;
	}
	if (req->data_len) {
		if (rt->len + req->data_len > rt->cap) {
			rt->overflow = true;
		} else {
			memcpy(rt->body + rt->len, req->data, req->data_len);
			rt->len += req->data_len;
		}
	}
	if (status != HTTP_SERVER_DATA_FINAL) {
		return 0;
	}
	rt->body[rt->len] = '\0';

	struct api_resp r = {.status = HTTP_200_OK, .buf = resp_buf, .cap = sizeof(resp_buf)};

	if (!authorized(req)) {
		api_error(&r, HTTP_401_UNAUTHORIZED, "нужен пароль");
		resp->headers = auth_headers;
		resp->header_count = ARRAY_SIZE(auth_headers);
	} else if (rt->overflow) {
		api_error(&r, HTTP_413_PAYLOAD_TOO_LARGE, "запрос слишком большой");
	} else {
		rt->fn(client->method, rt->body, rt->len, &r);
		resp->headers = json_headers;
		resp->header_count = ARRAY_SIZE(json_headers);
	}
	release(rt);
	resp->status = r.status;
	resp->body = (const uint8_t *)resp_buf;
	resp->body_len = r.len;
	resp->final_chunk = true;
	return 0;
}

#define API(_name, _path, _methods, _fn, _big)                                                     \
	static struct route _name##_route = {.fn = _fn, .big_body = _big};                         \
	static struct http_resource_detail_dynamic _name##_detail = {                              \
		.common = {.type = HTTP_RESOURCE_TYPE_DYNAMIC,                                     \
			   .bitmask_of_supported_http_methods = _methods},                         \
		.cb = api_cb,                                                                      \
		.user_data = &_name##_route,                                                       \
	};                                                                                         \
	HTTP_RESOURCE_DEFINE(_name##_res, ws_http, _path, &_name##_detail)

#define GET  BIT(HTTP_GET)
#define POST BIT(HTTP_POST)
#define PUT  BIT(HTTP_PUT)

API(status, "/api/status", GET, api_status, false);
API(screens, "/api/screens", GET | PUT, api_screens, true);
API(validate, "/api/screens/validate", POST, api_screens_validate, true);
API(rollback, "/api/screens/rollback", POST, api_screens_rollback, false);
API(factory, "/api/screens/factory", POST, api_screens_factory, false);
API(catalog, "/api/catalog", GET, api_catalog, false);
API(glyphs, "/api/glyphs", GET, api_glyphs, false);
API(vars, "/api/vars", GET, api_vars, false);
API(dstate, "/api/display/state", GET, api_display_state, false);
API(render, "/api/render", POST, api_render, true);
API(preview, "/api/display/preview", POST, api_preview, true);
API(pin, "/api/display/pin", POST, api_pin, false);
API(settings, "/api/settings", GET | POST, api_settings, true);
API(scan, "/api/wifi/scan", GET, api_wifi_scan, false);
API(lamp, "/api/lamp", POST, api_lamp, false);

#ifdef CONFIG_WS_OTA
/* ---- firmware upload: streamed into slot 1, never buffered ---- */

HTTP_SERVER_REGISTER_HEADER_CAPTURE(ws_hdr_sha, "X-Image-Sha256");

static struct {
	bool active;
	bool failed;
	enum http_status status;
} up;

static const char *header(const struct http_request_ctx *req, const char *name)
{
	for (size_t i = 0; i < req->header_count; i++) {
		if (!strcasecmp(req->headers[i].name, name)) {
			return req->headers[i].value;
		}
	}
	return NULL;
}

static void upload_start(struct http_client_ctx *client, const struct http_request_ctx *req)
{
	uint8_t sha[32];
	const char *hex = header(req, "X-Image-Sha256");

	if (!authorized(req)) {
		up.failed = true;
		up.status = HTTP_401_UNAUTHORIZED;
		return;
	}
	if (hex && ws_unhex(hex, sha, sizeof(sha))) {
		up.failed = true;
		up.status = HTTP_400_BAD_REQUEST;
		return;
	}
	int ret = ws_ota_web_begin(client->content_len, hex ? sha : NULL);

	if (ret) {
		up.failed = true;
		up.status = ret == -EBUSY ? HTTP_409_CONFLICT : HTTP_400_BAD_REQUEST;
		return;
	}
	up.active = true;
}

static int ota_upload_cb(struct http_client_ctx *client, enum http_data_status status,
			 const struct http_request_ctx *req, struct http_response_ctx *resp,
			 void *user_data)
{
	if (status == HTTP_SERVER_DATA_ABORTED) {
		if (up.active) {
			ws_ota_web_finish(-ECONNABORTED);
		}
		memset(&up, 0, sizeof(up));
		return 0;
	}
	if (!up.active && !up.failed) {
		upload_start(client, req);
	}
	if (up.active && req->data_len && ws_ota_web_chunk(req->data, req->data_len)) {
		up.active = false;
		up.failed = true;
		up.status = HTTP_500_INTERNAL_SERVER_ERROR;
	}
	if (status != HTTP_SERVER_DATA_FINAL) {
		return 0;
	}
	enum http_status st = up.failed ? up.status : HTTP_200_OK;

	if (up.active && ws_ota_web_finish(0)) {
		st = HTTP_422_UNPROCESSABLE_ENTITY;
	}
	int n = ws_ota_status_json(resp_buf, sizeof(resp_buf));

	memset(&up, 0, sizeof(up));
	resp->status = st;
	resp->headers = st == HTTP_401_UNAUTHORIZED ? auth_headers : json_headers;
	resp->header_count = 2;
	resp->body = (const uint8_t *)resp_buf;
	resp->body_len = n > 0 ? n : 0;
	resp->final_chunk = true;
	return 0;
}

static struct http_resource_detail_dynamic ota_upload_detail = {
	.common = {.type = HTTP_RESOURCE_TYPE_DYNAMIC,
		   .bitmask_of_supported_http_methods = BIT(HTTP_POST)},
	.cb = ota_upload_cb,
};
HTTP_RESOURCE_DEFINE(ota_upload_res, ws_http, "/api/ota/upload", &ota_upload_detail);
API(ota, "/api/ota", GET | POST, api_ota, false);
#endif

int ws_web_start(void)
{
	int r = http_server_start();

	LOG_INF("web server on port %u: %d", http_port, r);
	return r;
}
