#!/usr/bin/env node
// Golden frames of the factory screens rendered by fw/web/src/render.js.
//
//   node fw/web/tools/golden-screens.js [--check]
//
// Writes fw/tests/golden/screens_golden.json and screens_golden_gen.h; the
// ztest suite "screens" renders the same screens with the C renderer and
// compares them bit for bit.
'use strict';
const fs = require('fs');
const path = require('path');
const R = require('../src/render.js');

const ROOT = path.resolve(__dirname, '../../..');
const glyphs = JSON.parse(fs.readFileSync(path.join(ROOT, 'fw/web/src/glyphs.json'), 'utf8'));
const factory = JSON.parse(fs.readFileSync(path.join(ROOT, 'fw/lib/screens/factory_screens.json'), 'utf8'));
const OUT_JSON = path.join(ROOT, 'fw/tests/golden/screens_golden.json');
const OUT_H = path.join(ROOT, 'fw/tests/golden/screens_golden_gen.h');

const hours = Array.from({ length: 12 }, (_, i) => [Math.round(-2 + 5 * Math.sin(i / 3)), i >= 5 && i <= 8 ? 70 : 10]);

// Variable sets in natural units, as /api/vars reports them.
const SETS = {
  day: {
    'out.t': -2, 'out.cond': 'pcloud', 'out.wind': 5, 'out.wind_dir': 'nw', 'out.rh': 78, 'out.p': 748,
    'fc.tmax': 4, 'fc.tmin': -7, 'fc.rain_from': 15, 'fc.rain_to': 19, 'fc.rain_in': 150,
    'fc.ice': false, 'fc.hours': hours, 'fc.age': 30, 'obs.age': 99999,
    'in.t': 22.1, 'in.rh': 41, 'in.co2': 640, 'in.p': 747, 'in.p_trend': -1.5,
    'time.hour': 12, 'time.min': 30, 'time.dow': 3,
  },
  ice_stuffy: {
    'out.t': 12, 'out.cond': 'rain', 'out.wind': 11, 'out.wind_dir': 'se', 'out.rh': 95, 'out.p': 731,
    'fc.tmax': 13, 'fc.tmin': 0, 'fc.rain_from': -1, 'fc.rain_to': -1, 'fc.ice': true,
    'in.t': -0.4, 'in.rh': 23, 'in.co2': 1240, 'in.p': 731, 'in.p_trend': 2,
    'time.hour': 7, 'time.min': 5, 'time.dow': 1,
  },
  unknown: {},
  worst: {
    'out.t': -35, 'out.cond': 'storm', 'out.wind': 25, 'out.wind_dir': 'sw', 'out.rh': 100, 'out.p': 799,
    'fc.tmax': -35, 'fc.tmin': -35, 'fc.rain_from': 23, 'fc.rain_to': 2, 'fc.ice': false,
    'fc.hours': hours.map(([t, p]) => [t - 30, p]),
    'in.t': -35.5, 'in.rh': 100, 'in.co2': 2000, 'in.p': 799, 'in.p_trend': 0,
    'time.hour': 23, 'time.min': 59, 'time.dow': 7,
  },
};
const SODS = [0, 30, 60, 90];

function frameBytes(f) {
  const b = new Array(141).fill(0);
  for (let i = 0; i < f.length; i++) if (f[i]) b[i >> 3] |= 1 << (i & 7);
  return b;
}
function rows(f) {
  const r = [];
  for (let y = 0; y < R.H; y++) r.push(Array.from(f.slice(y * R.W, (y + 1) * R.W)).map((v) => (v ? '#' : '.')).join(''));
  return r;
}
const cStr = (s) => JSON.stringify(s);

function cVar(name, v) {
  const t = R.VARS[name];
  if (t === 'hours') return null;
  if (t === 'num') return `{${cStr(name)}, ${Math.sign(v) * Math.floor(Math.abs(v) * 10 + 0.5 + 1e-9)}, 0}`;
  if (t === 'bool') return `{${cStr(name)}, ${v ? 1 : 0}, 0}`;
  if (t === 'cond') return `{${cStr(name)}, ${glyphs.cond.indexOf(v)}, 0}`;
  if (t === 'dir') return `{${cStr(name)}, ${glyphs.dirs.indexOf(v)}, 0}`;
  return `{${cStr(name)}, 0, ${cStr(String(v))}}`;
}

function render() {
  const r = R.create(glyphs);
  const json = { sets: SETS, frames: [] };
  const h = ['/* Generated by fw/web/tools/golden-screens.js (render.js). Do not edit. */',
    '#ifndef SCREENS_GOLDEN_GEN_H_', '#define SCREENS_GOLDEN_GEN_H_', '#include <stdint.h>', '',
    'struct gs_var { const char *name; int32_t num; const char *str; };',
    'struct gs_set { const char *name; const struct gs_var *vars; int n; const int16_t (*hours)[2]; int n_hours; };',
    'struct gs_frame { int set; const char *screen; int32_t sod; uint8_t frame[141]; };', ''];
  const sets = [];
  Object.entries(SETS).forEach(([name, vars], si) => {
    const vs = Object.entries(vars).map(([k, v]) => cVar(k, v)).filter(Boolean);
    h.push(`static const struct gs_var gs_vars_${si}[] = {${vs.length ? vs.join(', ') : '{0, 0, 0}'}};`);
    const hs = vars['fc.hours'] || [];
    h.push(`static const int16_t gs_hours_${si}[][2] = {${hs.length ? hs.map(([t, p]) => `{${t}, ${p}}`).join(', ') : '{0, 0}'}};`);
    sets.push(`{${cStr(name)}, gs_vars_${si}, ${vs.length}, gs_hours_${si}, ${hs.length}}`);
  });
  h.push(`static const struct gs_set gs_sets[] = {\n\t${sets.join(',\n\t')}\n};\n`);
  const frames = [];
  Object.entries(SETS).forEach(([name, vars], si) => {
    for (const sc of factory.screens) {
      for (const sod of SODS) {
        const ncfg = r.normalize(factory); // fresh hysteresis state per frame
        const f = r.renderScreen(ncfg, sc.id, vars, sod);
        json.frames.push({ set: name, screen: sc.id, sod, frame: rows(f) });
        frames.push(`{${si}, ${cStr(sc.id)}, ${sod}, {${frameBytes(f).map((b) => '0x' + b.toString(16).padStart(2, '0')).join(',')}}}`);
      }
    }
  });
  h.push(`static const struct gs_frame gs_frames[] = {\n\t${frames.join(',\n\t')}\n};\n`);
  h.push('#endif\n');
  return [[OUT_JSON, JSON.stringify(json, null, 1) + '\n'], [OUT_H, h.join('\n')]];
}

function main() {
  const checkOnly = process.argv.includes('--check');
  let stale = false;
  for (const [file, content] of render()) {
    const old = fs.existsSync(file) ? fs.readFileSync(file, 'utf8') : null;
    if (old === content) continue;
    if (checkOnly) { console.error(`stale: ${path.relative(ROOT, file)}`); stale = true; continue; }
    fs.writeFileSync(file, content);
    console.log(`wrote ${path.relative(ROOT, file)}`);
  }
  if (stale) { console.error('Run: node fw/web/tools/golden-screens.js'); process.exit(1); }
}
if (require.main === module) main();
module.exports = { SETS };
